spring.application.name=cart-service
server.port=8082

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=cart-service;encrypt=false
spring.datasource.username=sa
spring.datasource.password=1234567890
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false